DTS-STN/next-template

package-lock.json
package.json
postcss.config.js
styles/globals.css
tailwind.config.js

added tailwind with JIT mode on. Also added some basic focus styles to all components.

Add tailwind

---

.github/README.md

- added some basic readme headers + some text to give a general idea of what else to write
-

added some headers and stuff to the Readme

---

.github/README.md
LICENSE

adding a description to the template to remove/approve MIT
including the official ESDC copyright statement

Adding some licence notes for use of template

---

package.json

- Adding a joint test script so all tests can be run with one command `npm test`
-
`npm test`

adding joint test script

---

cypress/integration/app.spec.js

added another test file to test the badge

---

.github/README.md
.github/pull_request_template.md
.github/workflows/comment-environment.yml

The purpose of this PR is to add automatic URL commenting as a GitHub action. I've also updated a typo on the PR template.
-
-
1. Comments should appear with URLs to next-template dev server.

Added Automatic URL Commenting + Typo Fix

---

.github/README.md
package-lock.json
package.json
styles/globals.css
tailwind.config.js

The purpose of this PR is to upgrade Tailwind to v3 following [the official upgrade guide](https://tailwindcss.com/docs/upgrade-guide). I've also added the tailwind typography plugin.
- We could explore adding some default custom colors that align with the Canada.ca theme 
1. Pull in branch
2. Try adding tailwind classes to an element on `index.js`
3. Ensure styling still works

Update Tailwind to v3

---

.github/README.md
__tests__/pages/home.test.js
locales/en.js
locales/fr.js
next.config.js
package-lock.json
pages/index.js
styles/Home.module.css

Basic setup for i18n
- locales setup 
- i18n next.config setup 
- language selection button
- download and run

DTSCI 79 - i18n setup 

---

.gitignore
components/Header.js
jest.config.js
package.json
pages/_app.js

Updated _app.js to import locales and use pageProps as locale. This fixes the EN-FR button not changing the language.
- Updated _app.js to import locales and use pageProps as locale.
- Fixed issue with Header.js not changing English/French display link text
- Adjusted the test:coverage script to generate the json-summary report in /coverage. This should be deployed to gh-pages for future use in badges.

DTSCI-98 Fix issue with Locale changes

---

Dockerfile
next.config.js
package.json

minor fixes for secirty header eand packages for docker files

---

.teamcity/settings.kts

This PR adds dynamic branching to our repo. When a PR is opened, the branch will be deployed.

Dynamic branching

---

.github/README.md
.teamcity/settings.kts
package-lock.json

This PR adds a missing closing quote to `settings.kts` and adds the missing `NEXT_CMS_URL` env var to the new build type.

Fixed issue with dynamic branching

---

__tests__/pages/404.test.js
__tests__/pages/_error.test.js
pages/404.js
pages/_error.js

Added dynamic error page _error.js that displays an error page whenever an error is called with any status code. The page displays the status code as a part of the error display. 
- Renders dynamic error page in English and French
- 404 Page can be displayed by going to a non-existent directory
- The error page is currently styled with Tailwind as it includes the _app.js Layout component which also makes use of Tailwind styles. This can be changed to minimize styling should there be a tailwind error, however, the Layout component would still cause styling errors.

DTSCI-99 Add Error Pages

---

__tests__/pages/404.test.js
__tests__/pages/home.test.js
__tests__/pages/index.test.js
components/Header.js
components/MetaData.js
pages/_app.js
pages/_error.js
pages/api/metrics.js
pages/home.js

Using mock and direct call to be able to test getStaticProps 
- Updated home.test
- Updated Index.test
- Updated 404.test
- Added ignore flags to the rest of the files where coverage wasn't 100%
- Review Code

 testing getStaticProps example and Ignore flags examples

---

.github/workflows/load-test.yml
load-test.js

Adding k6 as a performance/load testing system through github actions.
The test is scheduled to run every night.
This PR is an introduction to k6. The only test built for now are the HTTP requests to our fonts and our main branch.

Load Testing

---

.github/workflows/load-test.yml

Changing load-test timing.

---

.github/workflows/load-test.yml

Making load-tests run every 24 hours.

Last commit for load-test timimg.

---

.github/workflows/load-test.yml
.teamcity/settings.kts

Creating a Performance environment in TeamCity.

Creating a performance environment.

---

.teamcity/settings.kts

Changing the name of URL for our perf environment.

Perf environment

---

.github/workflows/load-test.yml

Load tests passed and now I am just changing them back to a 24-hour cycle.

load-test every 24 hours.

---

package-lock.json
package.json

Updated Next from 12.1.0 to 12.1.1 to fix issues with next/Image
minimist was also patched to fix a high vulnerability

Updated next to version 12.1.1

---

.vscode/launch.json

just a nice existing configuration for VS Code debugging

adding a configuration for debugging in vscode

---

.github/README.md
.github/workflows/comment-environment.yml
.teamcity/settings.kts

Updating the TC kotlin scripts to include 'dyna-' tag in the dynamic urls, adding a cleanup script for dyna deployments.  Minor other cleanups (redundant VCS root).

updating kotlin scripts

---

.teamcity/settings.kts

adding back performance

---

helm/charts/next-template/templates/ingress.yaml
helmfile/overrides/next-template/next-template.yaml.gotmpl

Pond helm updates

---

.github/README.md

- Make the case of the "c" in the word 'Coverage' in the badges all match. Make them all uppercase.
- Remove the "Deployments" section of the readme
- Remove the "Useful Links" section of the readme
Check the README to make sure Coverage is written with an uppercase letter and that the "Deployments" and "Useful Links" sections are removed.

Readme changes

---

__tests__/components/DateModified.test.js
__tests__/components/Footer.test.js
__tests__/components/Header.test.js
__tests__/components/Layout.test.js

- Move test files to a consistent location

move test files

---

.env.example
lib/logger.js
next.config.js
pages/_app.js
pages/home.js

Adding Logging Framework
1. Multiple logging states added. `debug    info    warn    error    trace` Do we want to remove some?
2. While running it locally, all logs will appear. In production, only if you insert `?debug=true` will the logs appear. Do we want a different approach? Something like: Never show logs in prod. Or is the current logic okay?

Adding logging system.

---

pages/_error.js

Fixed error page props

---

src/pages/index.tsx

- remove attributes that cause warnings because of the switch from Next 12 => Next 13

[frontend] upgrade Image component to be compatible with Next13

---

next.config.js
package-lock.json
src/pages/home.tsx

- remove commented code
- add current date locale string instead of DATE-NA in config

[frontend] cleanup

---

Dockerfile
package-lock.json
package.json

Upgrade node image.  Re-add package-lock file since there was a CI issue.  Remove duplicate dependency in package.

upgrade node image
